import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas:            "var(--color-canvas)",
        surface:           "var(--color-surface)",
        "surface-card":    "var(--color-surface-card)",
        "surface-elevated":"var(--color-surface-elevated)",
        "border-subtle":   "var(--color-border-subtle)",
        "border-strong":   "var(--color-border-strong)",
        "text-primary":    "var(--color-text-primary)",
        "text-secondary":  "var(--color-text-secondary)",
        brand:             "#2F81F7",
        "brand-blue":      "#2F81F7",
        recovery:          "#10B981",
        "recovery-teal":   "#14B8A6",
        sanitize:          "#EF4444",
        "sanitize-dialog": "#2A1215",
        "status-success":  "#22C55E",
        "status-warning":  "#F59E0B",
        "status-error":    "#DC2626",
        "status-info":     "#38BDF8",
        "status-wipe":     "#A78BFA",
        ink:               "#060a12",
        panel:             "var(--color-surface)",
        line:              "var(--color-border-subtle)",
        signal:            "#2F81F7",
        "signal-teal":     "#14B8A6",
        "signal-violet":   "#A78BFA",
        danger:            "#EF4444",
        card:              "var(--color-surface-card)",
        "card-foreground": "var(--color-text-primary)",
        popover:           "var(--color-surface)",
        "popover-foreground": "var(--color-text-primary)",
        muted:             "var(--color-surface-elevated)",
        "muted-foreground":"var(--color-text-secondary)",
        cyan: {
          400: "#38bdf8",
          500: "#2F81F7",
          600: "#0284c7",
        },
      },
      boxShadow: {
        panel:           "0 20px 60px rgba(0,0,0,0.5)",
        glow:            "0 0 20px rgba(47,129,247,0.22)",
        "glow-strong":   "0 0 35px rgba(47,129,247,0.4)",
        "glow-teal":     "0 0 20px rgba(20,184,166,0.22)",
        "glow-rose":     "0 0 20px rgba(239,68,68,0.22)",
        "glow-emerald":  "0 0 20px rgba(16,185,129,0.22)",
        "glow-violet":   "0 0 20px rgba(167,139,250,0.25)",
        "glow-purple":   "0 0 20px rgba(167,139,250,0.25)",
        "glow-amber":    "0 0 20px rgba(245,158,11,0.22)",
      },
      animation: {
        "glow-line":  "glow-line 3s ease-in-out infinite",
        "slide-down": "slide-down 0.2s ease-out forwards",
        "scale-in":   "scale-in 0.25s cubic-bezier(0.34,1.56,0.64,1) forwards",
        "fade-up":    "fade-up 0.4s ease-out forwards",
        "float":      "float 3s ease-in-out infinite",
        "glow-pulse": "glow-pulse-cyan 2.5s ease-in-out infinite",
      },
      transitionDuration: {
        "400": "400ms",
      },
    },
  },
  plugins: [],
} satisfies Config;
