"""Add sanitization tables

Revision ID: 347f6038569a
Revises: b29c8448c05d
Create Date: 2026-09-07 23:14:21.017553
"""
from alembic import op
import sqlalchemy as sa


revision = '347f6038569a'
down_revision = 'b29c8448c05d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

