"""Add target_file_path to sanitization

Revision ID: 62fd7b3f69b1
Revises: 347f6038569a
Create Date: 2026-09-07 23:32:28.817507
"""
from alembic import op
import sqlalchemy as sa


revision = '62fd7b3f69b1'
down_revision = '347f6038569a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanitization_jobs', sa.Column('target_file_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanitization_jobs', 'target_file_path')
    # ### end Alembic commands ###

