"""Add forensic models

Revision ID: 90788dd4e65a
Revises: 62fd7b3f69b1
Create Date: 2026-09-07 23:55:44.120018
"""
from alembic import op
import sqlalchemy as sa


revision = '90788dd4e65a'
down_revision = '62fd7b3f69b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forensic_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('case_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_cases_case_id'), 'forensic_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_forensic_cases_id'), 'forensic_cases', ['id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('filesystem', sa.String(length=50), nullable=True),
    sa.Column('partition_table', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_evidence_id'), 'evidence_items', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_items_id'), 'evidence_items', ['id'], unique=False)
    op.create_table('chain_of_custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hash_value', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_of_custody_id'), 'chain_of_custody', ['id'], unique=False)
    op.create_table('recovered_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=True),
    sa.Column('output_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('filesystem', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_allocated', sa.Boolean(), nullable=True),
    sa.Column('recovery_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovered_files_id'), 'recovered_files', ['id'], unique=False)
    op.create_index(op.f('ix_recovered_files_recovery_id'), 'recovered_files', ['recovery_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovered_files_recovery_id'), table_name='recovered_files')
    op.drop_index(op.f('ix_recovered_files_id'), table_name='recovered_files')
    op.drop_table('recovered_files')
    op.drop_index(op.f('ix_chain_of_custody_id'), table_name='chain_of_custody')
    op.drop_table('chain_of_custody')
    op.drop_index(op.f('ix_evidence_items_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_forensic_cases_id'), table_name='forensic_cases')
    op.drop_index(op.f('ix_forensic_cases_case_id'), table_name='forensic_cases')
    op.drop_table('forensic_cases')
    # ### end Alembic commands ###

