"""Add sanitization models

Revision ID: b29c8448c05d
Revises: c390cb7c0c8d
Create Date: 2026-09-07 23:13:24.671188
"""
from alembic import op
import sqlalchemy as sa


revision = 'b29c8448c05d'
down_revision = 'c390cb7c0c8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanitization_jobs_job_id'), table_name='sanitization_jobs')
    op.drop_table('sanitization_jobs')
    op.drop_table('sanitization_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanitization_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=32), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['sanitization_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanitization_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('device_path', sa.VARCHAR(length=256), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=128), nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=256), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=64), nullable=False),
    sa.Column('pattern', sa.VARCHAR(length=64), nullable=False),
    sa.Column('passes', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('bytes_processed', sa.INTEGER(), nullable=False),
    sa.Column('progress_percent', sa.FLOAT(), nullable=False),
    sa.Column('verification_method', sa.VARCHAR(length=64), nullable=True),
    sa.Column('verification_scope', sa.VARCHAR(length=64), nullable=True),
    sa.Column('verification_result', sa.VARCHAR(length=64), nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('certificate_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('certificate_hash', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanitization_jobs_job_id'), 'sanitization_jobs', ['job_id'], unique=1)
    # ### end Alembic commands ###

