"""Add usb metadata fields

Revision ID: c390cb7c0c8d
Revises: 20260907_0001
Create Date: 2026-09-07 19:28:35.718842
"""
from alembic import op
import sqlalchemy as sa


revision = 'c390cb7c0c8d'
down_revision = '20260907_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('usb_version', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('manufacturer', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('device_class', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_class')
    op.drop_column('devices', 'manufacturer')
    op.drop_column('devices', 'usb_version')
    # ### end Alembic commands ###

