import type { DeviceListResponse, UsbDeviceDetail, DeviceAnalysis, FileBrowserResponse, EvidenceListResponse, VerificationResult } from "../types/device";
import type { RecoveryScanResponse, RestoreFileResponse } from "./recoveryApi";

export const MOCK_DEVICES: UsbDeviceDetail[] = [
  {
    id: "usb_sandisk_extreme_64gb",
    device_path: "\\\\.\\PHYSICALDRIVE1",
    vendor: "SanDisk",
    model: "Extreme USB 3.2 Flash Drive",
    serial: "AA01092837482910",
    capacity_bytes: 64000000000,
    size_bytes: 64000000000,
    filesystem: "exFAT",
    mount_point: "E:\\",
    removable: true,
    read_only: false,
    transport: "usb",
    device_type: "USB_STORAGE",
    system_disk: false,
    is_protected: false,
    is_usb: true,
    analysis_available: true,
    detected_at: new Date().toISOString(),
    partitions: [
      {
        name: "PHYSICALDRIVE1p1",
        device_path: "\\\\.\\PHYSICALDRIVE1p1",
        filesystem: "exFAT",
        label: "EVIDENCE_USB",
        uuid: "8472-9102",
        capacity_bytes: 64000000000,
        mount_points: ["E:\\"],
      },
    ],
  },
  {
    id: "usb_samsung_t7_500gb",
    device_path: "\\\\.\\PHYSICALDRIVE2",
    vendor: "Samsung",
    model: "Portable SSD T7 Shield",
    serial: "S5B1NS0R819283X",
    capacity_bytes: 500107862016,
    size_bytes: 500107862016,
    filesystem: "NTFS",
    mount_point: "F:\\",
    removable: true,
    read_only: false,
    transport: "usb",
    device_type: "USB_STORAGE",
    system_disk: false,
    is_protected: false,
    is_usb: true,
    analysis_available: true,
    detected_at: new Date().toISOString(),
    partitions: [
      {
        name: "PHYSICALDRIVE2p1",
        device_path: "\\\\.\\PHYSICALDRIVE2p1",
        filesystem: "NTFS",
        label: "CASE_STORE",
        uuid: "F4A2D819-0129",
        capacity_bytes: 500107862016,
        mount_points: ["F:\\"],
      },
    ],
  },
  {
    id: "wpd_pixel_8_pro",
    device_path: "\\\\.\\WPD\\USB_VID_18D1_PID_4EE1",
    vendor: "Google",
    model: "Pixel 8 Pro (Internal Storage)",
    serial: "39201JEHN01928",
    capacity_bytes: 128000000000,
    size_bytes: 128000000000,
    filesystem: "MTP",
    mount_point: "\\\\.\\WPD\\Pixel_Storage",
    removable: true,
    read_only: false,
    transport: "usb",
    device_type: "MOBILE_DEVICE",
    system_disk: false,
    is_protected: false,
    is_usb: true,
    analysis_available: true,
    detected_at: new Date().toISOString(),
    partitions: [
      {
        name: "Internal Shared Storage",
        device_path: "\\\\.\\WPD\\Pixel_Storage",
        filesystem: "MTP",
        label: "Phone Storage",
        uuid: null,
        capacity_bytes: 128000000000,
        mount_points: ["\\\\.\\WPD\\Pixel_Storage"],
      },
    ],
  },
];

export const MOCK_DEVICE_LIST_RESPONSE: DeviceListResponse = {
  devices: MOCK_DEVICES,
  refreshed_at: new Date().toISOString(),
  demo_mode: true,
  warning: null,
};

export const MOCK_DELETED_FILES: RecoveryScanResponse = {
  device_id: "usb_sandisk_extreme_64gb",
  device_name: "SanDisk Extreme USB 3.2 Flash Drive (E:\\)",
  scan_type: "raw_carver",
  scanned_at: new Date().toISOString(),
  total_found: 5,
  files: [
    {
      id: "carved_pdf_001",
      filename: "Confidential_Financial_Audit_2025.pdf",
      original_path: "E:\\Documents\\Financials\\Confidential_Financial_Audit_2025.pdf",
      source_path: "Cluster #192040 (Carved from Unallocated Space)",
      size_bytes: 2845012,
      extension: ".pdf",
      category: "Document",
      deleted_at: "2026-09-08T14:32:00Z",
      confidence: "HIGH",
      confidence_score: 100,
      validation_details: "Valid PDF: %PDF-1.7 header + EOF catalog xref validated",
      offset_bytes: 98304000,
      recovery_method: "Raw Carver (EXT)",
      recoverable: true,
    },
    {
      id: "carved_png_002",
      filename: "surveillance_screenshot_cctv_frame.png",
      original_path: "E:\\DCIM\\Camera\\surveillance_screenshot_cctv_frame.png",
      source_path: "Cluster #284102",
      size_bytes: 1420980,
      extension: ".png",
      category: "Image",
      deleted_at: "2026-09-09T08:15:00Z",
      confidence: "HIGH",
      confidence_score: 98,
      validation_details: "Valid PNG: IHDR/IDAT chunks verified + CRC32 passed (1920x1080 RGB)",
      offset_bytes: 145890000,
      recovery_method: "Raw Carver (EXT)",
      recoverable: true,
    },
    {
      id: "carved_docx_003",
      filename: "Board_Meeting_Minutes_Sanitization_Plan.docx",
      original_path: "E:\\Work\\Board_Meeting_Minutes_Sanitization_Plan.docx",
      source_path: "Cluster #391024",
      size_bytes: 842100,
      extension: ".docx",
      category: "Document",
      deleted_at: "2026-09-10T11:45:00Z",
      confidence: "HIGH",
      confidence_score: 95,
      validation_details: "Valid OOXML: Central Directory verified [word/document.xml detected]",
      offset_bytes: 200450000,
      recovery_method: "Raw Carver (EXT)",
      recoverable: true,
    },
    {
      id: "carved_mp4_004",
      filename: "laboratory_access_footage_cam02.mp4",
      original_path: "E:\\Recordings\\laboratory_access_footage_cam02.mp4",
      source_path: "Cluster #512000",
      size_bytes: 18450000,
      extension: ".mp4",
      category: "Media",
      deleted_at: "2026-09-07T19:20:00Z",
      confidence: "MEDIUM",
      confidence_score: 85,
      validation_details: "Valid ISO BMFF: ftyp box (isom) + moov atom header valid",
      offset_bytes: 262144000,
      recovery_method: "Raw Carver (EXT)",
      recoverable: true,
    },
    {
      id: "ntfs_recycle_005",
      filename: "employee_master_credentials.xlsx",
      original_path: "E:\\HR\\employee_master_credentials.xlsx",
      source_path: "E:\\.BIN\\S-1-5-21\\.xlsx",
      size_bytes: 195000,
      extension: ".xlsx",
      category: "Document",
      deleted_at: "2026-09-11T09:10:00Z",
      confidence: "HIGH",
      confidence_score: 100,
      validation_details: "NTFS  index header authentic filename decoded: employee_master_credentials.xlsx",
      offset_bytes: 31020000,
      recovery_method: "NTFS .BIN",
      recoverable: true,
    },
  ],
};

export const MOCK_HISTORY_JOBS = [
  {
    job_id: "JOB-NIST-8821",
    target_file_path: "\\\\.\\PHYSICALDRIVE1 (SanDisk 64GB)",
    pattern: "zero",
    method: "NIST SP 800-88 Clear",
    completed_at: "2026-09-11T16:20:00Z",
    status: "COMPLETED",
    sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  },
  {
    job_id: "JOB-DOD-7719",
    target_file_path: "E:\\Evidence_Archive_2025.zip",
    pattern: "dod5220",
    method: "DoD 5220.22-M 3-Pass",
    completed_at: "2026-09-10T12:05:00Z",
    status: "COMPLETED",
    sha256: "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e",
  },
];
